<a href="https://colab.research.google.com/github/head1ton/EURI_ML/blob/main/face_emotion_detection/face_emotion_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install mediapipe

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 1.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.6/35.6 MB 14.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 29.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 294.6/294.6 kB 15.8 MB/s eta 0:00:00
  Attempting uninstall: protobuf
    Found existing installation: protobuf 5.29.4
    Uninstalling protobuf-5.29.4:
      Successfully uninstalled protobuf-5.29.4
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
grpcio-status 1.71.0 requires protobuf<6.0dev,>=5.26.1, but you have protobuf 4.25.6 which is incompatible.


In [2]:
!pip install numpy==1.23.5

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.1/17.1 MB 28.8 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
chex 0.1.89 requires numpy>=1.24.1, but you have numpy 1.23.5 which is incompatible.
pymc 5.21.1 requires numpy>=1.25.0, but you have numpy 1.23.5 which is incompatible.
tensorflow 2.18.0 requires numpy<2.1.0,>=1.26.0, but you have numpy 1.23.5 which is incompatible.
xarray 2025.1.2 requires numpy>=1.24, but you have numpy 1.23.5 which is incompatible.
blosc2 3.2.0 requires numpy>=1.26, but you have numpy 1.23.5 which is incompatible.
albucore 0.0.23 requires numpy>=1.24.4, but you have numpy 1.23.5 which is incompatible.
jax 0.5.2 requires numpy>=1.25, but you have numpy 1.23.5 which is 

In [1]:
!pip install --upgrade --force-reinstall mediapipe

  Using cached mediapipe-0.10.21-cp311-cp311-manylinux_2_28_x86_64.whl.metadata (9.7 kB)
  Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
  Using cached protobuf-4.25.6-cp37-abi3-manylinux2014_x86_64.whl.metadata (541 bytes)
  Using cached sounddevice-0.5.1-py3-none-any.whl.metadata (1.4 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.0/62.0 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.9/101.9 kB 10.2 MB/s eta 0:00:00
Using cached mediapipe-0.10.21-cp311-cp311-manylinux_2_28_x86_64.whl (35.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.8/63.8 kB 3.6 MB/s eta 0:00:00
Using cached numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
Using cached protobuf-4.25.6-cp37-abi3-manylinux2014_x86_64.whl (294 kB)
Using cached sounddevice-0.5.1-py3-none-any.whl (32 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 277.3/277.3 kB 15.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━

In [2]:
!unzip face_small.zip -d /content/data

Archive:  face_small.zip
   creating: /content/data/faces/
  inflating: /content/data/__MACOSX/._faces  
   creating: /content/data/faces/happy/
  inflating: /content/data/__MACOSX/faces/._happy  
  inflating: /content/data/faces/.DS_Store  
  inflating: /content/data/__MACOSX/faces/._.DS_Store  
   creating: /content/data/faces/sad/
  inflating: /content/data/__MACOSX/faces/._sad  
   creating: /content/data/faces/angry/
  inflating: /content/data/__MACOSX/faces/._angry  
   creating: /content/data/faces/surprised/
  inflating: /content/data/__MACOSX/faces/._surprised  
  inflating: /content/data/faces/happy/0065.png  
  inflating: /content/data/__MACOSX/faces/happy/._0065.png  
  inflating: /content/data/faces/happy/0071.png  
  inflating: /content/data/__MACOSX/faces/happy/._0071.png  
  inflating: /content/data/faces/happy/0059.png  
  inflating: /content/data/__MACOSX/faces/happy/._0059.png  
  inflating: /content/data/faces/happy/0058.png  
  inflating: /content/data/__MACOSX/fac

In [1]:
import cv2
import mediapipe as mp


def get_face_landmarks(image, draw=False, static_image_mode=True):

    # Read the input image
    image_input_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    face_mesh = mp.solutions.face_mesh.FaceMesh(static_image_mode=static_image_mode,
                                                max_num_faces=1,
                                                min_detection_confidence=0.5)
    image_rows, image_cols, _ = image.shape
    results = face_mesh.process(image_input_rgb)

    image_landmarks = []

    if results.multi_face_landmarks:

        if draw:

            mp_drawing = mp.solutions.drawing_utils
            mp_drawing_styles = mp.solutions.drawing_styles
            drawing_spec = mp_drawing.DrawingSpec(thickness=2, circle_radius=1)

            mp_drawing.draw_landmarks(
                image=image,
                landmark_list=results.multi_face_landmarks[0],
                connections=mp.solutions.face_mesh.FACEMESH_CONTOURS,
                landmark_drawing_spec=drawing_spec,
                connection_drawing_spec=drawing_spec)

        ls_single_face = results.multi_face_landmarks[0].landmark
        xs_ = []
        ys_ = []
        zs_ = []
        for idx in ls_single_face:
            xs_.append(idx.x)
            ys_.append(idx.y)
            zs_.append(idx.z)
        for j in range(len(xs_)):
            image_landmarks.append(xs_[j] - min(xs_))
            image_landmarks.append(ys_[j] - min(ys_))
            image_landmarks.append(zs_[j] - min(zs_))

    return image_landmarks

/usr/local/lib/python3.11/dist-packages/jaxlib/plugin_support.py:71: RuntimeWarning: JAX plugin jax_cuda12_plugin version 0.5.1 is installed, but it is not compatible with the installed jaxlib version 0.5.3, so it will not be used.
  warnings.warn(


In [2]:
import os
import cv2
import numpy as np

data_dir = '/content/data/faces'

output = []
for emotion_index, emotion in enumerate(sorted(os.listdir(data_dir))):
    e = emotion
    for i, image_path_ in enumerate(sorted(os.listdir(os.path.join(data_dir, emotion)))):
        image_path = os.path.join(data_dir, emotion, image_path_)

        if image_path_.lower().endswith(('.png', '.jpg', '.jpeg')):
            image = cv2.imread(image_path)

            if image is not None:
                face_landmarks = get_face_landmarks(image)

                face_landmarks.append(int(emotion_index))
                output.append(face_landmarks)
            else:
                print(f"Warning: Could not read image at path: {image_path}")
        else:
            print(f"Skipping non-image file: {image_path_}")

np.savetxt('data.txt', np.asarray(padded_output))

Skipping non-image file: .DS_Store
Skipping non-image file: .DS_Store
Skipping non-image file: .DS_Store
Skipping non-image file: .DS_Store


In [3]:
!head -n 10 data.txt

3.665238618850708008e-02 2.941192686557769775e-01 7.296533882617950439e-02 8.237570524215698242e-03 2.364568412303924561e-01 4.860229790210723877e-02 4.103773832321166992e-02 2.543179094791412354e-01 7.515054568648338318e-02 2.216884493827819824e-02 1.780107319355010986e-01 7.020826637744903564e-02 5.473613739013671875e-03 2.189671099185943604e-01 4.478475451469421387e-02 1.533919572830200195e-02 1.962426602840423584e-01 4.740557819604873657e-02 5.047634243965148926e-02 1.388839185237884521e-01 6.937151402235031128e-02 3.874325752258300781e-02 1.178383529186248779e-01 1.906485706567764282e-01 6.015819311141967773e-02 9.679856896400451660e-02 7.200433313846588135e-02 5.802297592163085938e-02 7.559373974800109863e-02 6.839832849800586700e-02 7.120907306671142578e-02 4.150867462158203125e-04 7.408484816551208496e-02 3.808844089508056641e-02 3.036916553974151611e-01 7.463663257658481598e-02 4.266095161437988281e-02 3.120863139629364014e-01 7.850481942296028137e-02 4.819741845130920410e-02 

In [4]:
import pickle

import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix

data_file = "data.txt"
data = np.loadtxt(data_file)

X = data[:, :-1]
y = data[:, -1]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True, stratify=y)

rf_classifier = RandomForestClassifier()

rf_classifier.fit(X_train, y_train)

y_pred = rf_classifier.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy * 100:.2f}%")
print(confusion_matrix(y_test, y_pred))

with open('./model', 'wb') as f:
    pickle.dump(rf_classifier, f)

Accuracy: 53.75%
[[10  1  7  4]
 [ 1 17  2  0]
 [ 8  1  6  4]
 [ 5  1  3 10]]


In [6]:
import pickle
import cv2

emotions = ["ANGRY", "HAPPY", "SAD", "SURPRISED"]

with open('./model', 'rb') as f:
    model = pickle.load(f)

cap = cv2.VideoCapture(0)

while True:
    ret, frame = cap.read()
    if not ret:
        break

    face_landmarks = get_face_landmarks(frame, draw=True, static_image_mode=False)

    output = model.predict([face_landmarks])

    cv2.putText(frame, emotions[int(output[0])], (10, frame.shape[0] - 1), cv2.FONT_HERSHEY_SIMPLEX, 3, (0, 255, 0), 5)

    cv2.imshow('frame', frame)

    cv2.waitKey(25)

cap.release()
cv2.destroyAllWindows()